---
- name: Check if downloadable archive exists
  stat: path={{ downloads }}/spark-{{ spark_version }}-cdh{{ cdh_version }}.tar.gz
  register: archive

- name: Get Spark binary
  get_url: url=http://archive.cloudera.com/cdh{{ cdh_major }}/cdh/{{ cdh_major }}/spark-{{ spark_version }}-cdh{{ cdh_version }}.tar.gz dest={{ downloads }} timeout=100
  when: archive.stat.exists == false
  tags:
  - download

- name: Check if unpacked archive exists
  stat: path={{ install_dir }}/spark-{{ spark_version }}-cdh{{ cdh_version }}
  register: unpacked

- name: Unarchive Spark binary
  unarchive: copy=no src={{ downloads }}/spark-{{ spark_version }}-cdh{{ cdh_version }}.tar.gz dest={{ install_dir }}
  when: unpacked.stat.exists == false
  tags:
  - extract

- name: Copy RELEASE file
  copy: src=RELEASE dest={{ install_dir }}/spark-{{ spark_version }}-cdh{{ cdh_version }}
  tags:
  - bugfix

- name: Add hadoop stuff to spark classpath (for spark 1.5)
  copy: src=spark-env.sh dest={{ install_dir }}/spark-{{ spark_version }}-cdh{{ cdh_version }}/conf
  tags:
  - configs